{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "ca085ce5_d3349bc0",
        "filename": "/COMMIT_MSG",
        "patchSetId": 5
      },
      "lineNbr": 26,
      "author": {
        "id": 1012732
      },
      "writtenOn": "2021-02-16T21:25:47Z",
      "side": 1,
      "message": "Same comment as in another open review of ours; should follow the existing standard.",
      "range": {
        "startLine": 26,
        "startChar": 0,
        "endLine": 26,
        "endChar": 66
      },
      "revId": "bc4baef533db12fc94b4f342e42020af361d178e",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "aad4ed10_8549dddf",
        "filename": "/COMMIT_MSG",
        "patchSetId": 5
      },
      "lineNbr": 26,
      "author": {
        "id": 1083195
      },
      "writtenOn": "2021-02-17T12:38:35Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "ca085ce5_d3349bc0",
      "range": {
        "startLine": 26,
        "startChar": 0,
        "endLine": 26,
        "endChar": 66
      },
      "revId": "bc4baef533db12fc94b4f342e42020af361d178e",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "8e3439cd_4d314bdb",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1012732
      },
      "writtenOn": "2021-02-16T21:25:47Z",
      "side": 1,
      "message": "A nit. As for the CI failure, there is already the Issue 14083 logged to report it.",
      "revId": "bc4baef533db12fc94b4f342e42020af361d178e",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}